config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!,except: [:index]
  before_action :set_post,except:[:index,:new,:create]
  before_action :user_check,only:[:edit]
  def index
    @posts = Post.all
  end
  
  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_stp)
    redirect_to root_path
  end

  def edit

  end

  def update
    if @post.update(post_stp)
      return redirect_to root_path
    else 
      render 'edit'
    end
  end


  def destroy
    if @post.destroy
      redirect_to root_path
    else
      render 'edit'
    end
  end
  
  def post_stp
    params.require(:post).permit(:text).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def user_check
    if current_user != @post.user
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Changer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
  <%= form_with model: @post,url: post_path, local: true do |f| %>
    <%= f.text_area :text %>
    <%= f.submit "投稿" %>
  <% end %>


   <%= link_to '削除', post_path(@post), method: :delete %>

app/views/posts/index.html.erb
<% if user_signed_in? %>
  <li><%= current_user.email %></li>
  <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
  <li><%= link_to '投稿', new_post_path %></li>
<% else %>
  <li><%= link_to 'ログイン', new_user_session_path %></li>
  <li><%= link_to '新規登録', new_user_registration_path %></li>
<% end %>



<% @posts.each do |post|%>
  <br>
  内容：<%= post.text %>
  投稿者：<%= post.user.email %>
  <% if user_signed_in? && current_user == post.user %>
    <%= link_to '編集', edit_post_path(post), method: :get %>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<% if user_signed_in? %>
  <%= form_with model: @post ,url: posts_path, local: true do |f| %>
    <%= f.text_area :text %>
    <%= f.submit "投稿" %>
  <% end %>
<% else %>
<% end %>